print("Mustafa" + "Alsadoud")
print("Mustafa" + "5")
name = input("What is your name?")
print(name)
age = input("How old are you?")
print(age)
address = input("What is your address?")
print(address)
print("{}is{}and lives in this address{}.". fromat("name", "age", "address"))
